# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[â¯](purple)' # The symbol when the last command succeeded

# Disable the package module, hiding it from the prompt completely
[package]
[git_branch]
symbol = 'î‚  '
format = '[$symbol$branch]($style)'
style = 'bold yellow'
truncation_length = 4
truncation_symbol = 'â€¦'

[git_status]
format = '([$all_statuses]($style) )'
style = 'red'
disabled = false
conflicted = 'ğŸ’¥'
ahead = 'â‡¡'
behind = 'â‡£'
staged = 'â—'
modified = 'âœš'
deleted = 'âœ–'
untracked = 'â€¦'
stashed = 'âš‘'
renamed = 'âœ'
